# Generated by Django 3.2.24 on 2024-10-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
